---
title: "Preliminary_data_exploration"
output: html_document
---

```{r, message, error=FALSE, warning=FALSE}
library(tidyverse)
library(tidyr)
library(scales)
library(gridExtra)
library(plotly)
library(DT)
```
Pulls out all different types of championships/tournaments/etc. based on regex for game in notes column. 
```{r,message, error=FALSE, warning=FALSE, fig.height=7}
jep_data <- read_tsv("../data/jeopardy_clue_dataset-master/master_season1-35.tsv")

jep_data %>% 
  filter(round == "3",
         value > "0")

tournaments <- jep_data %>% 
  mutate(tournaments = notes == str_match_all(string = notes, pattern = ".*game.*")) %>%
  filter(tournaments == TRUE)
```
Counts Daily doubles and total # of rounds. 
```{r,message, error=FALSE, warning=FALSE, fig.height=7}
daily_doubles <- tournaments %>% 
  group_by(round, air_date, daily_double) %>% 
  count(total_rounds = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = round)) +
  geom_bar(aes(fill = daily_double)) +
  ggtitle("Daily Doubles in each round of tournaments for 1-35 seasons", subtitle = "") +
  labs(x = "Jeopardy Rounds 1-3", y = "Number of Rounds") +
  geom_text(stat='count', aes(label=..count..), vjust=-1) +
  theme_bw() +
  scale_fill_viridis_d()
daily_doubles
```
What was the highest daily double bet? Was it higher in tournaments?
```{r, warning=FALSE, message=FALSE, error=FALSE}
#need to plot/facet non tournaments
tournament_graph <- tournaments %>% 
  select(-c(comments:question, notes)) %>% 
  filter(daily_double == "yes") %>% 
  arrange(desc(value, air_date)) %>% 
  ggplot(aes(value, air_date)) +
  geom_point(aes(color = round)) +
  ggtitle("Tournaments") +
  facet_grid("round")
all_rounds <- jep_data %>% 
  select(-c(comments:question, notes)) %>% 
  filter(daily_double == "yes") %>% 
  arrange(desc(value, air_date)) %>% 
  ggplot(aes(value, air_date)) +
  geom_point(aes(color = round)) + 
  ggtitle("All Games") +
  facet_grid("round") 

all_rounds <- ggplotly(all_rounds)
tournament_graph <- ggplotly(tournament_graph)

subplot(all_rounds, tournament_graph, nrows = 2)
```

```{r}
season_1 <- read_tsv("../data/jeopardy_clue_dataset-master/season1.tsv") %>% 
  filter(round == "1")
datatable(season_1)
```

