---
title: |
  | The most difficult school subject
  | (according to Jeopardy)
author: "Jacob Fontenot, Burton Karger, Eric Wendt, Caroline Wendt"
date: "12/13/2019"
output:
  beamer_presentation:
    colortheme: wolverine
    theme: Szeged
  ioslides_presentation: default
subtitle: ERHS 535
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE, warning=FALSE, error = FALSE)
```


# Overview

## Research question

What are the most important and most difficult school subjects according to Jeopardy?

## Introduction

- Initial data investigation showed subject bias
- Prompted us to consider traditional school subjects
- Decided to compare "Jeopardy-based" education to public school education

## Methods: Overview

- Created a dataframe of school subjects and related terms (from Quizlet)
- Separated Jeopardy dataset into 6 subjects (science, math, history, english, geography, and art) by "joining" it with the Quizlet dataframe


## Methods: Joining dataframes

- Converted all Jeopardy data and school subject data to lowercase and removed all special characters
- Randomly sampled 155 vocab terms from school subject data 
- Used `inner_join` from the `dplyr` pacakage to match a the "question" to a specific vocab term
- Grouped the "questions" by subject

## Methods: Determining subject importance and difficulty using joined dataframe

- Discovered answer value changes after November 26, 2001 and decided to separate data into two catagories
- Calculated number of occurances of each school subject (most important subject)
- Calculated average value of all "answers" for each school subject (most difficult subject)
- Graphed results using interactive heat map faceted by round and date

## Results


## Results


## Results


## Conclusions


# Tutorial

## Overview: Approach in R

## Packages and techniques

## Lessons learned



## References

