---
title: "According to Jeopardy! Which school subject is the most valuable?"
output: 
  flexdashboard::flex_dashboard:
    theme: journal
---

```{r, include=FALSE}
library(flexdashboard)
library(viridis)
library(forcats)
library(ggthemes)
library(RColorBrewer)
library(tidyverse)
library(tidyr)
library(scales)
library(gridExtra)
library(plotly)
library(DT)
library(readr)
library(dplyr)
library(stringr)
library(fuzzyjoin)
library(kableExtra)
```

```{r, include=FALSE}
# jeopardy data
jeop_data <- read_tsv(
  file = "../data/jeopardy_clue_dataset-master/master_season1-35.tsv") %>%
  dplyr::mutate(question = stringr::str_to_lower(question)) %>%
  dplyr::mutate(question = stringr::str_remove_all(question,
                                                   "[^[:alnum:][:blank:]]"))
```

```{r, include=FALSE}
# subjects and terms data
sub_term_data <- read_csv("../data/subjects_and_terms.csv") %>%
  rename(vocab_term = Term,
      subject = Subject) %>%
  dplyr::mutate(vocab_term = 
                  stringr::str_to_lower(vocab_term)) %>%
  dplyr::mutate(vocab_term = 
                  stringr::str_remove_all(vocab_term,
                                          "[^[:alnum:][:blank:]]")) %>%
  dplyr::distinct() %>% 
  dplyr::mutate(question = vocab_term) %>% 
  dplyr::group_by(subject) %>%
  dplyr::sample_n(size = 155, replace = FALSE) %>% 
  dplyr::ungroup()
```

```{r, include=FALSE}
jeop_school_joined <- dplyr::inner_join(x = jeop_data, y = sub_term_data,
                                        by = "question")
```

```{r, include=FALSE}
# add column to distinguish whether episode used old or new value framework
jeop_school_joined <- jeop_school_joined %>% 
  dplyr::mutate(air_date_type = if_else(air_date < "2001-11-26", 
                                        "before", "after"))
```

```{r, include=FALSE}
# before November 26, 2001
jeop_school_summary_before <- jeop_school_joined %>%
  dplyr::filter(air_date_type %in% "before") %>% 
  dplyr::group_by(subject) %>% 
  dplyr::summarize(mean_value = round(mean(value), 2),
                   subject_total = round(n(), 2)) %>% 
  dplyr::ungroup() %>% 
  arrange(desc(subject_total))
```

```{r, include=FALSE}
# after November 26, 2001
jeop_school_summary_after <- jeop_school_joined %>%
  dplyr::filter(air_date_type %in% "after") %>% 
  dplyr::group_by(subject) %>% 
  dplyr::summarize(mean_value = round(mean(value), 2),
                   subject_total = round(n(), 2)) %>% 
  dplyr::ungroup() %>% 
  arrange(desc(subject_total))
```

```{r, include=FALSE}
after <- kable(jeop_school_summary_after) %>% 
  add_header_above(header = c(" " = 1, "Summary After November 26, 2001" = 2)) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>% 
  row_spec(2, bold = TRUE, color = "red") %>%
  row_spec(1, bold = TRUE, color = "blue")
```

```{r, include=FALSE}
before <- kable(jeop_school_summary_before) %>% 
  add_header_above(header = c(" " = 1, "Summary Before November 26, 2001" = 2))%>% 
  kable_styling(bootstrap_options = c("striped", "hover")) %>% 
  row_spec(1, bold = TRUE, color = "blue") %>% 
  row_spec(5, bold = TRUE, color = "red")

```

```{r, include=FALSE}
# data for round 1
heat_data_r1 <- jeop_school_joined %>%
  dplyr::filter(daily_double %in% "no",
                round == 1) %>% 
  dplyr::select(round, value, subject, air_date_type) %>%
  dplyr::mutate_at(vars(round, subject, air_date_type), 
                   funs(factor(.))) %>% 
  dplyr::group_by(round, value, subject, air_date_type) %>%
  count() %>%
  ungroup()

heat_data_r1 %>% 
  slice(1:5)
```


```{r, include=FALSE}
# interactive version of heat map for round 1
hmap_1_interact <- ggplot(heat_data_r1,
                          aes(x = subject, y = value)) +
  geom_tile(aes(fill = n)) +
  scale_fill_viridis(option = "viridis", direction = -1) +
  labs(x = "Subject", y = "Value", 
       fill = "Number of \noccurences",
       title = "Round 1: Number of occurences of subject by value") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 45)) +
  facet_grid( . ~ air_date_type, scales = "free_y")
  
ggplotly(hmap_1_interact)
```

```{r, include=FALSE}
# data for round 2
heat_data_r2 <- jeop_school_joined %>%
  dplyr::filter(daily_double %in% "no",
                round == 2) %>% 
  dplyr::select(round, value, subject, air_date_type) %>%
  dplyr::mutate_at(vars(round, subject, air_date_type), 
                   funs(factor(.))) %>% 
  dplyr::group_by(round, value, subject, air_date_type) %>%
  count() %>%
  ungroup()

heat_data_r2 %>% 
  slice(1:5)
```

```{r, include=FALSE}
# interactive version of heat map for round 2
hmap_2_interact <- ggplot(heat_data_r2, 
                          aes(x = subject, y = value)) +
  geom_tile(aes(fill = n)) +
  scale_fill_viridis(option = "magma", direction = -1) +
  labs(x = "Subject", y = "Value", 
       fill = "Number of \noccurences",
       title = "Round 2: Number of occurences of subject by value") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 45)) +
  facet_grid( . ~ air_date_type, scales = "free")
  
ggplotly(hmap_2_interact)
```


```{r, include=FALSE}
# data for daily doubles
heat_data_dd <- jeop_school_joined %>%
  dplyr::filter(daily_double %in% "yes") %>% 
  dplyr::select(daily_double, value, subject) %>%
  dplyr::mutate_at(vars(daily_double, subject), funs(factor(.))) %>% 
  dplyr::group_by(daily_double, value, subject) %>%
  count() %>%
  ungroup()

heat_data_dd %>% 
  slice(1:5)
```

```{r, include=FALSE}
# interactive version of heat map for daily doubles
hmap_dd_interact <- ggplot(heat_data_dd,
                          aes(x = subject, y = value)) +
  geom_tile(aes(fill = n)) +
  scale_fill_viridis(option = "cividis", direction = -1) +
  labs(x = "Subject", y = "Value",
       fill = "Number of \noccurences",
       title = "Daily Doubles: Number of occurences of subject by value") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 45))

ggplotly(hmap_dd_interact)
```

```{r, include=FALSE}
# data for double faceting
heat_data_df <- jeop_school_joined %>%
  dplyr::filter(daily_double %in% "no",
                round != 3) %>% 
  dplyr::select(round, value, subject, air_date_type) %>%
  dplyr::mutate_at(vars(round, subject, air_date_type), 
                   funs(factor(.))) %>% 
  dplyr::group_by(round, value, subject, air_date_type) %>%
  count() %>%
  ungroup()

heat_data_df %>% 
  slice(1:5)
```

```{r, include=FALSE}
# interactive version of heat map for rounds 1 and 2 faceted by date
hmap_4_interact <- ggplot(heat_data_df, 
                          aes(x = subject, y = value)) +
  geom_tile(aes(fill = n)) +
  scale_fill_viridis(option = "plasma", direction = -1) +
  labs(x = "Subject", y = "Value", 
       fill = "Number of \noccurences",
       title = "Number of occurences of subject by value") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 45),
        plot.title = element_text(size = 14),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12)) +
  facet_grid(round ~ air_date_type, scales = "free_y")  
  
ggplotly(hmap_4_interact)
```

Graphs
======================================================================
Column {.tabset data-width=500}
-----------------------------------------------------------------------

### Both Rounds

```{r}
hmap_4_interact
```

### Round 1

```{r}
hmap_1_interact
```

### Round 2

```{r}
hmap_2_interact
```


Column {data-width=500}
-----------------------------------------------------------------------
### Daily Doubles

```{r}
hmap_dd_interact
```


Tables {data-orientation=rows}
=======================================================================

Row {.tabset data-height=1000}
-----------------------------------------------------------------------

### Cleaned Data

```{r}
datatable(jeop_school_joined, options = list(
  pageLength = 25
))
```

### Term Data

```{r}
datatable(sub_term_data, options = list(
  pageLength = 25
))
```

Summary Statistics 
=======================================================================

Row {.tabset data-height=1000}
-----------------------------------------------------------------------

### Before November 26, 2001

```{r}
before
```

### After November 26, 2001

```{r}
after
```

